// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *projetos → Tecnologias*
 */
export interface ProjetosDocumentDataTecnologiasItem {
  /**
   * TecnologiasNome field in *projetos → Tecnologias*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projetos.tecnologias[].tecnologiasnome
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tecnologiasnome: prismic.KeyTextField;
}

type ProjetosDocumentDataSlicesSlice = never;

/**
 * Content for projetos documents
 */
interface ProjetosDocumentData {
  /**
   * Titulo field in *projetos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projetos.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * SubTitulo field in *projetos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projetos.subtitulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitulo: prismic.RichTextField;

  /**
   * DescriaoProjeto field in *projetos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projetos.descriaoprojeto
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descriaoprojeto: prismic.RichTextField;

  /**
   * LinkSite field in *projetos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projetos.linksite
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  linksite: prismic.RichTextField;

  /**
   * Tecnologias field in *projetos*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: projetos.tecnologias[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  tecnologias: prismic.GroupField<
    Simplify<ProjetosDocumentDataTecnologiasItem>
  >;

  /**
   * Slice Zone field in *projetos*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: projetos.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProjetosDocumentDataSlicesSlice>;
}

/**
 * projetos document from Prismic
 *
 * - **API ID**: `projetos`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjetosDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjetosDocumentData>,
    "projetos",
    Lang
  >;

export type AllDocumentTypes = ProjetosDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ProjetosDocument,
      ProjetosDocumentData,
      ProjetosDocumentDataTecnologiasItem,
      ProjetosDocumentDataSlicesSlice,
      AllDocumentTypes,
    };
  }
}
