// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Blog → content*
 */
export interface BlogDocumentDataConteudoItem {
  /**
   * title field in *Blog → content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.conteudo[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * subtitle field in *Blog → content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.conteudo[].subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * conteudo field in *Blog → content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.conteudo[].conteudo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;

  /**
   * imagens field in *Blog → content*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.conteudo[].imagens
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagens: prismic.ImageField<never>;
}

type BlogDocumentDataSlicesSlice = never;

/**
 * Content for Blog documents
 */
interface BlogDocumentData {
  /**
   * title field in *Blog*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * DescricaoCard field in *Blog*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.descricaocard
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descricaocard: prismic.RichTextField;

  /**
   * BannerCard field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.bannercard
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bannercard: prismic.ImageField<never>;

  /**
   * date field in *Blog*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.data
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  data: prismic.DateField;

  /**
   * content field in *Blog*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.conteudo[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  conteudo: prismic.GroupField<Simplify<BlogDocumentDataConteudoItem>>;

  /**
   * Slice Zone field in *Blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BlogDocumentData>, "blog", Lang>;

/**
 * Item in *GaleriaProjetos → imagens*
 */
export interface GaleriaprojetosDocumentDataImagensItem {
  /**
   * GaleriaImagens field in *GaleriaProjetos → imagens*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: galeriaprojetos.imagens[].galeriaimagens
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  galeriaimagens: prismic.ImageField<never>;
}

type GaleriaprojetosDocumentDataSlicesSlice = never;

/**
 * Content for GaleriaProjetos documents
 */
interface GaleriaprojetosDocumentData {
  /**
   * imagens field in *GaleriaProjetos*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: galeriaprojetos.imagens[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  imagens: prismic.GroupField<Simplify<GaleriaprojetosDocumentDataImagensItem>>;

  /**
   * Slice Zone field in *GaleriaProjetos*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: galeriaprojetos.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<GaleriaprojetosDocumentDataSlicesSlice> /**
   * Meta Title field in *GaleriaProjetos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: galeriaprojetos.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *GaleriaProjetos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: galeriaprojetos.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *GaleriaProjetos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: galeriaprojetos.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * GaleriaProjetos document from Prismic
 *
 * - **API ID**: `galeriaprojetos`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GaleriaprojetosDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<GaleriaprojetosDocumentData>,
    "galeriaprojetos",
    Lang
  >;

/**
 * Item in *projetos → Tecnologias*
 */
export interface ProjetosDocumentDataTecnologiasItem {
  /**
   * TecnologiasNome field in *projetos → Tecnologias*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projetos.tecnologias[].tecnologiasnome
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tecnologiasnome: prismic.KeyTextField;
}

type ProjetosDocumentDataSlicesSlice = never;

/**
 * Content for projetos documents
 */
interface ProjetosDocumentData {
  /**
   * Titulo field in *projetos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projetos.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * SubTitulo field in *projetos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projetos.subtitulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitulo: prismic.RichTextField;

  /**
   * DescriaoProjeto field in *projetos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projetos.descriaoprojeto
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descriaoprojeto: prismic.RichTextField;

  /**
   * LinkSite field in *projetos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projetos.linksite
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  linksite: prismic.RichTextField;

  /**
   * Tecnologias field in *projetos*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: projetos.tecnologias[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  tecnologias: prismic.GroupField<
    Simplify<ProjetosDocumentDataTecnologiasItem>
  >;

  /**
   * Slice Zone field in *projetos*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: projetos.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProjetosDocumentDataSlicesSlice>;
}

/**
 * projetos document from Prismic
 *
 * - **API ID**: `projetos`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjetosDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjetosDocumentData>,
    "projetos",
    Lang
  >;

export type AllDocumentTypes =
  | BlogDocument
  | GaleriaprojetosDocument
  | ProjetosDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogDocument,
      BlogDocumentData,
      BlogDocumentDataConteudoItem,
      BlogDocumentDataSlicesSlice,
      GaleriaprojetosDocument,
      GaleriaprojetosDocumentData,
      GaleriaprojetosDocumentDataImagensItem,
      GaleriaprojetosDocumentDataSlicesSlice,
      ProjetosDocument,
      ProjetosDocumentData,
      ProjetosDocumentDataTecnologiasItem,
      ProjetosDocumentDataSlicesSlice,
      AllDocumentTypes,
    };
  }
}
