import "./globals.css";
import Menu from "./Componentes/Menu";
import Info from "./Componentes/Info";
import Logo from "./Componentes/Logo";
import { JetBrains_Mono } from "next/font/google";

const fonte = JetBrains_Mono({ subsets: ["latin"] });

export const metadata = {
  title: "Portfólio - Arthur Gomes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body
        className={`${fonte.className} bg-colors-background  antialiased h-screen`}
      >
        <header className="container mx-auto text-center md:text-left mt-4 flex flex-col gap-8">
          <Logo />
          <div className="block md:hidden">
            <Menu />
          </div>
        </header>
        <main className="">
          <div className="container  mx-auto flex flex-col  md:flex md:flex-row gap-4 mt-[20px]">
            <Info />
            <div>
              <div className="hidden md:block">
                <Menu />
              </div>
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
